### PR TITLE
Gbuzykin/yet another formatter added for compare

### PR DESCRIPTION
**Pull request by gbuzykin**
Here is another formmater (mine) for compare with such an interesting result.
BTW Why do you output `fmtlib` result using default `{}` precision (6 digs) settings while other libs (clib, stdlib and mine) use 17 dig precision `{:.17}`? So, I fixed it and the time increased twice.

Here is the result:
```
Verifying ryu                  ... Error: expect 0.1 but actual 1E-1
Error: expect 0.12 but actual 1.2E-1
Error: expect 0.123 but actual 1.23E-1
Error: expect 0.1234 but actual 1.234E-1
Error: expect 1.2345 but actual 1.2345E0
OK. Length Avg = 22.027, Max = 24
Verifying doubleconv           ... OK. Length Avg = 22.420, Max = 25
Verifying fmt                  ... Error: expect 0.1 but actual 0.10000000000000001
Error: expect 1.2345 but actual 1.2344999999999999
OK. Length Avg = 22.935, Max = 24
Verifying fpconv               ... OK. Length Avg = 22.444, Max = 25
Verifying grisu2               ... OK. Length Avg = 21.975, Max = 25
Verifying milo                 ... OK. Length Avg = 21.975, Max = 25
Verifying ostringstream        ... Error: expect 0.1 but actual 0.10000000000000001
Error: expect 1.2345 but actual 1.2344999999999999
OK. Length Avg = 22.935, Max = 24
Verifying ostrstream           ... Error: expect 0.1 but actual 0.10000000000000001
Error: expect 1.2345 but actual 1.2344999999999999
OK. Length Avg = 22.935, Max = 24
Verifying sprintf              ... Error: expect 0.1 but actual 0.10000000000000001
Error: expect 1.2345 but actual 1.2344999999999999
OK. Length Avg = 22.935, Max = 24
Verifying util                 ... Error: expect 0.1 but actual 0.10000000000000001
Error: expect 1.2345 but actual 1.2344999999999999
OK. Length Avg = 22.935, Max = 24
Benchmarking randomdigit ryu                  ... [  34.000ns,   53.200ns]
Benchmarking randomdigit doubleconv           ... [  59.100ns,  109.800ns]
Benchmarking randomdigit fmt                  ... [  96.900ns,  116.200ns]
Benchmarking randomdigit fpconv               ... [  88.400ns,  141.300ns]
Benchmarking randomdigit grisu2               ... [  57.700ns,   86.600ns]
Benchmarking randomdigit milo                 ... [  44.400ns,   78.100ns]
Benchmarking randomdigit null                 ... [   1.200ns,    1.200ns]
Benchmarking randomdigit ostringstream        ... [ 893.000ns, 1051.000ns]
Benchmarking randomdigit ostrstream           ... [ 862.500ns,  997.600ns]
Benchmarking randomdigit sprintf              ... [ 590.600ns,  716.500ns]
Benchmarking randomdigit util                 ... [  58.000ns,   66.100ns]
```
The last line `util` is mine.
Compiled with `clang-12 -O3` Ubuntu 20.4

### CODE REVIEW

**Comment by gbuzykin** [comment]
`util` has an implementation of inversed string -> double conversion as well

**Comment by vitaut** [comment]
Thanks for the PR but this is just a fork of https://github.com/miloyip/dtoa-benchmark so please submit to the original repo.

**Comment by gbuzykin** [comment]
> Thanks for the PR but this is just a fork of https://github.com/miloyip/dtoa-benchmark so please submit to the original repo.

I know that it's a fork, but the comment and test results was address to `fmtlib` team.
I'll submit it to https://github.com/miloyip/dtoa-benchmark anyway.
Thanks!

**Comment by vitaut** [comment]
The reason why some algorithms use precision of 17 is for round trip. {fmt}, grisu and ryu don't need this because they provide round-trip guarantee by default (with the shortest repr).

**Comment by gbuzykin** [comment]
> The reason why some algorithms use precision of 17 is for round trip. {fmt}, grisu and ryu don't need this because they provide round-trip guarantee by default (with the shortest repr).

1) Could you clarify this point?
If we use default `{}` we suppose default precision of maximum 6 significant digits (as we know from standard spec).
And in this case I get roundtrip failure, for example
```
Error: roundtrip fail -2.541438786288762e+250 -> '-2.54144e+250' -> -2.5414400000000001e+250
```
How does {fmt} pass roundtrip test with only 6 digits? 6 digits are not enough to restore all `2.541438786288762e+250`. How comes?

2) And how about performance tests? C and C++ libs use prec=17

**Comment by vitaut** [comment]
The default is not 6 digit precision but the shortest decimal representation with the round-trip guarantee (currently using the Dragonbox algorithm: https://github.com/jk-jeon/dragonbox). This may produce up to 17 digits depending on the value, e.g.

```c++
#include <fmt/core.h>
#include <math.h>

int main() {
  fmt::print("{}\n", M_PI); // prints 3.141592653589793
}
```

In this case 16 digits is enough for round trip.

https://godbolt.org/z/dMoWev5js

**Comment by gbuzykin** [comment]
> The default is not 6 digit precision but the shortest decimal representation with the round-trip guarantee (currently using the Dragonbox algorithm: https://github.com/jk-jeon/dragonbox). This may produce up to 17 digits depending on the value, e.g.
> 
> ```c++
> #include <fmt/core.h>
> #include <math.h>
> 
> int main() {
>   fmt::print("{}\n", M_PI); // prints 3.141592653589793
> }
> ```
> 
> In this case 16 digits is enough for round trip.
> 
> https://godbolt.org/z/dMoWev5js

Ahh, I see. Thanks for clarifications!

**Pull request closed without merging**
